spring.application.name=service-a
server.port=8080

# OpenTelemetry Configuration
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.metrics.distribution.percentiles-histogram.http.server.requests=true
